# Generated by Django 4.1.7 on 2023-03-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
